### ISSUE TITLE
The relative position of the parent has been set, but the viewhelper position is incorrect, how can it be correct?

### ISSUE THREAD

**Issue by WREQI** [Fennec-hub/viewHelper#1]
![image](https://github.com/Fennec-hub/viewHelper/assets/35467304/6524fb85-4473-439f-8c03-e5ec1c5e595b)
![微信截图_20240318103347](https://github.com/Fennec-hub/viewHelper/assets/35467304/b879faec-1f25-4492-a98d-b3b22b7af0c7)

**Comment by WREQI** [comment]
The x,y of viewport seems to be technically based on the parent container

**Comment by Fennec-hub** [comment]
As promised, here is the new repo:
https://github.com/Fennec-hub/three-viewport-gizmo

Try offset with the options param

**Comment by WREQI** [comment]
![image](https://github.com/Fennec-hub/viewHelper/assets/35467304/a9d9d4f8-d215-4e05-a9b3-af464aa9c6af)
![image](https://github.com/Fennec-hub/viewHelper/assets/35467304/3484740c-b7d6-427f-b777-646095314a31)
![image](https://github.com/Fennec-hub/viewHelper/assets/35467304/6434bcde-a826-45a4-a5d2-02fa0223861a)
I looked at your new repository and it doesn't seem to solve the previous case of parent container offset, I currently use the height of the parent container to set it correctly. Seems you need to check and update your new repository down? @Fennec-hub

**Comment by Fennec-hub** [comment]
If I follow you correctly, the offset should be computed from the container, not the canvas?

**Comment by Fennec-hub** [comment]
@WREQI 
Fixed, switched to container offsetHeight, please try again and let me know.
